"""Keep the Norse part of the website light (PR-07).

The website is the whole repository, served by GitHub Pages from `main`.
PR-07 (29 Sept 2026): for Norse, commit only what the website uses, and
serve smaller copies of the postcard images and the print PDFs.

Run from anywhere after rebuilding a postcard image or a print PDF:

    python NorseBackpack/Tools/build_web_assets.py

It does four things:

1. Points Norse page links at web copies instead of the full-size files:
   postcard images under NorseBackpack/Postcards/ become WebP copies in
   NorseBackpack/Web/Postcards/, and PDFs under output/pdf/ become
   150 dpi copies in NorseBackpack/Web/pdf/. Only quoted paths are
   rewritten (src/href attributes and JS strings), never prose.
2. Rebuilds any web copy that is missing or older than its source.
3. Crawls the site from index.html and rewrites the Norse block in
   .gitignore: binary files under NorseBackpack/ are ignored unless the
   site uses them; output/pdf/ and output/docx/ are ignored outright.
   Text sources (.py, .md, .html, .js, .css, .json, .svg) stay committed.
4. With --untrack, runs `git rm --cached` on tracked files that are now
   ignored. The files stay on disk; only git stops tracking them.

The full-size files remain the print masters on this computer.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NORSE = "NorseBackpack/"
WEB = "NorseBackpack/Web/"

IMG_SRC = "NorseBackpack/Postcards/"
PDF_SRC = "output/pdf/"
IMG_MAX_SIDE = 1200
IMG_QUALITY = 82
PDF_DPI = 150

# Binary types under NorseBackpack/ that are ignored unless the site uses them.
BINARY_EXT = [".png", ".jpg", ".jpeg", ".webp", ".gif", ".tif", ".tiff",
              ".pdf", ".pptx", ".docx", ".xlsx", ".stl", ".3mf", ".zip",
              ".dxf", ".dwg", ".psd", ".ttf", ".otf", ".mp4", ".mov"]
ALWAYS_IGNORED = ["output/pdf/", "output/docx/"]

BEGIN = "# >>> Norse web assets (PR-07) - generated by NorseBackpack/Tools/build_web_assets.py"
END = "# <<< Norse web assets"

REF_RE = re.compile(
    r'''(?:href|src|data-src|poster)\s*=\s*["']([^"'#?]+)'''
    r'''|url\(\s*["']?([^"')#?]+)'''
    r'''|["'`]([^"'`\s<>]+\.(?:png|jpe?g|webp|svg|gif|pdf|css|js|html|json|woff2?|ttf|otf|mp4|glb|stl|csv|txt|zip))["'`]''',
    re.I)
TEXT_EXT = (".html", ".css", ".js", ".json")


def rel(p: Path) -> str:
    return p.resolve().relative_to(ROOT).as_posix()


def resolve(ref: str, base_dir: str) -> str | None:
    if re.match(r"^(https?:|data:|mailto:|javascript:|//|\$\{)", ref):
        return None
    ref = urllib.parse.unquote(ref)
    q = os.path.normpath(os.path.join(base_dir, ref)).replace("\\", "/")
    return q if (ROOT / q).is_file() else None


def crawl() -> set[str]:
    """Every file reachable from index.html through local links."""
    seen, queue = set(), ["index.html"]
    while queue:
        p = queue.pop()
        if p in seen or not (ROOT / p).is_file():
            continue
        seen.add(p)
        if not p.lower().endswith(TEXT_EXT):
            continue
        txt = (ROOT / p).read_text(encoding="utf-8", errors="ignore")
        base = os.path.dirname(p)
        for m in REF_RE.finditer(txt):
            q = resolve(next(g for g in m.groups() if g), base)
            if q:
                queue.append(q)
    return seen


def web_path(src: str) -> str | None:
    """Web-copy path for a full-size source, or None if it is not converted."""
    low = src.lower()
    if src.startswith(IMG_SRC) and low.endswith((".png", ".jpg", ".jpeg")):
        return WEB + "Postcards/" + str(Path(src[len(IMG_SRC):]).with_suffix(".webp").as_posix())
    if src.startswith(PDF_SRC) and low.endswith(".pdf"):
        return WEB + "pdf/" + src[len(PDF_SRC):]
    return None


def rewrite_links(pages: set[str]) -> dict[str, str]:
    """Point quoted references in Norse pages at web copies. Returns src -> web."""
    mapping: dict[str, str] = {}
    for page in sorted(pages):
        if not (page.startswith(NORSE) and page.lower().endswith(TEXT_EXT)):
            continue
        if page.startswith(WEB):
            continue
        path = ROOT / page
        raw = path.read_bytes()
        txt = raw.decode("utf-8")
        base = os.path.dirname(page)
        changed = False

        def swap(m: re.Match) -> str:
            nonlocal changed
            quote, ref, end = m.group(1), m.group(2), m.group(3)
            src = resolve(ref, base)
            dst = web_path(src) if src else None
            if not dst:
                return m.group(0)
            mapping[src] = dst
            new_ref = os.path.relpath(ROOT / dst, ROOT / base).replace("\\", "/")
            changed = True
            return f"{quote}{new_ref}{end}"

        # Quoted strings and url(...) only, so prose inside <code> is left alone.
        txt2 = re.sub(r'''(["'`(])([^"'`()\s<>]+\.(?:png|jpe?g|pdf))(["'`)])''', swap, txt, flags=re.I)
        if changed and txt2 != txt:
            path.write_bytes(txt2.encode("utf-8"))
            print(f"links updated: {page}")
        # Paths built at runtime (`...${slug}...`) cannot be rewritten or crawled.
        runtime = re.compile(r"(?<!Web/)(?:Postcards/|output/pdf/)[^`'\"\s<>]*\$\{[^}]*\}[^`'\"\s<>]*")
        for m in runtime.finditer(txt2):
            if not re.search(r"\.(?:png|jpe?g|pdf)$", m.group(0), re.I):
                continue
            line = txt2.count("\n", 0, m.start()) + 1
            print(f"WARNING {page}:{line}: runtime path to a full-size file, "
                  f"point it at {WEB} by hand: {m.group(0)}")
    return mapping


def build_image(src: Path, dst: Path) -> None:
    from PIL import Image
    im = Image.open(src)
    im.load()
    if max(im.size) > IMG_MAX_SIDE:
        im.thumbnail((IMG_MAX_SIDE, IMG_MAX_SIDE), Image.LANCZOS)
    if im.mode not in ("RGB", "RGBA"):
        im = im.convert("RGBA" if "A" in im.getbands() or "transparency" in im.info else "RGB")
    dst.parent.mkdir(parents=True, exist_ok=True)
    im.save(dst, "WEBP", quality=IMG_QUALITY, method=6)


def build_pdf(src: Path, dst: Path) -> None:
    import pymupdf
    doc = pymupdf.open(src)
    doc.rewrite_images(dpi_threshold=PDF_DPI + 10, dpi_target=PDF_DPI, quality=80)
    dst.parent.mkdir(parents=True, exist_ok=True)
    doc.save(dst, garbage=4, deflate=True, clean=True)
    doc.close()
    if dst.stat().st_size >= src.stat().st_size:
        shutil.copy2(src, dst)  # already light; keep the original bytes


def build_copies(sources: set[str]) -> None:
    for src in sorted(sources):
        dst = web_path(src)
        s, d = ROOT / src, ROOT / dst
        if d.is_file() and d.stat().st_mtime >= s.stat().st_mtime:
            continue
        (build_pdf if src.lower().endswith(".pdf") else build_image)(s, d)
        print(f"web copy: {dst}  ({s.stat().st_size / 1e6:.1f} -> {d.stat().st_size / 1e6:.2f} MB)")


def existing_web_sources() -> set[str]:
    """Sources behind web copies already linked from the site (for reruns)."""
    out = set()
    for d in (ROOT / WEB / "Postcards").rglob("*.webp") if (ROOT / WEB / "Postcards").is_dir() else []:
        stem = rel(d)[len(WEB + "Postcards/"):-len(".webp")]
        for ext in (".png", ".jpg", ".jpeg"):
            if (ROOT / (IMG_SRC + stem + ext)).is_file():
                out.add(IMG_SRC + stem + ext)
    for d in (ROOT / WEB / "pdf").glob("*.pdf") if (ROOT / WEB / "pdf").is_dir() else []:
        if (ROOT / PDF_SRC / d.name).is_file():
            out.add(PDF_SRC + d.name)
    return out


def write_gitignore(reachable: set[str]) -> None:
    keep = sorted(p for p in reachable
                  if p.startswith(NORSE) and Path(p).suffix.lower() in BINARY_EXT)
    lines = [BEGIN,
             "# Norse commits only what the website uses. Binary files under",
             "# NorseBackpack/ are ignored unless listed with ! below. Rerun the",
             "# script to refresh this block; do not edit it by hand."]
    lines += ALWAYS_IGNORED
    lines += [f"{NORSE}**/*{ext}" for ext in BINARY_EXT]
    lines += ["!" + re.sub(r"([\[\]*?\\])", r"\\\1", p) for p in keep]
    lines.append(END)
    block = "\n".join(lines) + "\n"

    gi = ROOT / ".gitignore"
    txt = gi.read_text(encoding="utf-8") if gi.is_file() else ""
    if BEGIN in txt:
        pre, rest = txt.split(BEGIN, 1)
        post = rest.split(END, 1)[1].lstrip("\n") if END in rest else ""
        txt = pre + block + post
    else:
        txt = txt.rstrip("\n") + "\n\n" + block
    gi.write_text(txt, encoding="utf-8")
    print(f".gitignore: Norse block written, {len(keep)} site files kept")


def untrack() -> None:
    out = subprocess.run(["git", "ls-files", "-ci", "--exclude-standard", "-z"],
                         cwd=ROOT, capture_output=True, check=True).stdout.decode()
    files = [f for f in out.split("\0") if f]
    if not files:
        print("nothing to untrack")
        return
    for i in range(0, len(files), 200):
        subprocess.run(["git", "rm", "--cached", "--quiet", "--"] + files[i:i + 200],
                       cwd=ROOT, check=True)
    print(f"untracked {len(files)} files (still on disk)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--untrack", action="store_true",
                    help="git rm --cached tracked files that the new rules ignore")
    args = ap.parse_args()

    mapping = rewrite_links(crawl())
    build_copies(set(mapping) | existing_web_sources())
    write_gitignore(crawl())
    if args.untrack:
        untrack()
    return 0


if __name__ == "__main__":
    sys.exit(main())
