// Auto-generated by build_coin_stl.py — do not hand-edit, edit the script instead.
DIAMETER = 28.0;
THICKNESS = 2.0;
RELIEF = 0.6;
$fn = 128;

union() {
    cylinder(h=THICKNESS, d=DIAMETER, $fn=$fn);
    translate([0, 0, THICKNESS])
        linear_extrude(height=RELIEF)
            translate([-DIAMETER/2, -DIAMETER/2, 0])
                scale([DIAMETER/1000, DIAMETER/1000])
                    import("../01_dirham_common_print.svg", dpi=25.4);  // 1 SVG unit = 1mm; default 96dpi shrinks it
}
