"""Export Aud's map base into page-point coordinates for the in-browser designer (PZ-17).

Why this exists
---------------
The designer page has to draw exactly what the printed PDF draws, or anything placed in the
browser lands somewhere else on paper.  Rather than reimplement the Lambert conformal conic
projection in JavaScript and hope the two agree, this script runs the REAL build, takes its
projection function, and writes the resulting geometry out already converted to PDF page points.

The designer then works in page points 1:1 with the PDF, and whatever it exports can be drawn
straight onto the sheet with no transform at all.

Output: aud_base.js, assigning window.AUD_BASE.  Coordinates are PDF page points with y UP
(origin bottom-left), the same convention the build script uses; the designer flips for SVG.

Usage: python export_aud_base.py
"""

import io
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import build_trail_maps_pdf as M  # noqa: E402 -- requires the sys.path guard above

# The zoomed frame: same span as the first pass, panned EAST so the map content sits further
# left on the sheet and the land mass to the east comes into view. It is about 1.8x closer than
# the shipped map.
#
# Two constraints pin the pan, and they very nearly conflict:
#   * stop 1 (Dogurdarnes) must sit in grid column B. Column B spans x 94.1..154.7 pt; it
#     lands at 140.2.
#   * Bjarnarhofn -- decoy card AD's own site -- must stay on the sheet. At exact column-B
#     centre it fell 7 pt off the west edge; this pan keeps it 9 pt inside, at A4.
# build() asserts every stop projects inside the map area, so panning further fails loudly
# rather than silently cropping a stop away. Bjarnarhofn is NOT one of those asserted stops --
# it is a decoy card, not a visit -- so it is checked by hand here instead.
#
# Symbols placed in the designer are deliberately NOT to scale: a hedge drawn long enough to
# read as a sinuous line is far longer than any real hedge at this zoom. That is accepted --
# the sheet is a puzzle prop, not a survey.
#
# WARNING: designer placements are stored as page points, not coordinates. Re-panning this
# frame moves the coastline under them and they will NOT follow. Settle the frame before
# drawing anything that matters.
ZOOM_FRAME = (-22.9751, -20.5451, 64.08, 65.37)


def main():
    plan = json.loads((HERE / "Norse_Aunt_Route_Plan.json").read_text(encoding="utf-8"))
    corpus = M.load_corpus()
    cfg = dict(M.TRAILS["aud"])
    cfg["frame"] = ZOOM_FRAME
    # build() asserts every decorative label projects inside the map area, and at this zoom the
    # shipped ones do not -- ISLAND sits at lon -20.75, well east of the new frame. Their
    # placement is a design question for the zoomed sheet, not something to guess here, so they
    # are dropped for the export and their positions are reported below as still open.
    dropped = {k: cfg.get(k, []) for k in ("regions", "waters", "areas")}
    cfg["regions"], cfg["waters"], cfg["areas"] = [], [], []

    pt, rings, _lab, lo0, lo1, la0, la1 = M.build(
        "aud", cfg, plan, corpus, _return_geometry=True)

    mx0, my0, mx1, my1 = M.MX0, M.MY0, M.MX1, M.MY1

    def inside(x, y, pad=60):
        return mx0 - pad <= x <= mx1 + pad and my0 - pad <= y <= my1 + pad

    land = []
    for ring in rings:
        pts = [pt(lon, lat) for lon, lat in ring]
        if not any(inside(x, y) for x, y in pts):
            continue                      # wholly off-sheet: nothing to draw
        land.append([[round(x, 2), round(y, 2)] for x, y in pts])

    stops = []
    for s in sorted(plan["visits"]["aud"], key=lambda v: v["order"]):
        # Same plotted-position shift the printed sheet uses, or the designer would place
        # symbols against a coastline the sheet does not draw.
        dlat, dlon = M.plot_nudge(s["name"])
        x, y = pt(s["lng"] + dlon, s["lat"] + dlat)
        stops.append({"name": s["name"], "order": s["order"],
                      "x": round(x, 2), "y": round(y, 2)})

    towns = {}
    for name, lat, lng in corpus:
        if lo0 <= lng <= lo1 and la0 <= lat <= la1:
            towns.setdefault(name, (lat, lng))
    town_list = []
    for name, (lat, lng) in sorted(towns.items()):
        dlat, dlon = M.plot_nudge(name)
        x, y = pt(lng + dlon, lat + dlat)
        if inside(x, y, pad=0):
            town_list.append({"name": name, "x": round(x, 2), "y": round(y, 2)})

    areas = []
    for name, lat, lng in dropped["areas"]:
        x, y = pt(lng, lat)
        if inside(x, y, pad=0):
            areas.append({"name": name, "x": round(x, 2), "y": round(y, 2)})

    base = {
        "note": "Generated by export_aud_base.py. Page points, y UP. Do not hand-edit.",
        "page": {"w": M.PAGE_W, "h": M.PAGE_H},
        "mapArea": {"x0": mx0, "y0": my0, "x1": mx1, "y1": my1},
        "neat": {"x0": M.NEAT[0], "y0": M.NEAT[1], "x1": M.NEAT[2], "y1": M.NEAT[3]},
        "grid": {"cols": M.GRID_COLS, "rows": M.GRID_ROWS},
        "frame": {"lon0": lo0, "lon1": lo1, "lat0": la0, "lat1": la1},
        "band": cfg["band"],
        "title": cfg["title"],
        "land": land,
        "stops": stops,
        "towns": town_list,
        "areas": areas,
    }

    out = HERE / "aud_base.js"
    io.open(out, "w", encoding="utf-8", newline="\n").write(
        "// Generated by export_aud_base.py -- do not hand-edit.\n"
        "window.AUD_BASE = " + json.dumps(base, ensure_ascii=False, indent=1) + ";\n")

    print("-> %s" % out.name)
    print("   frame lon %.2f..%.2f lat %.2f..%.2f" % (lo0, lo1, la0, la1))
    print("   %d land rings | %d stops | %d towns | %d areas"
          % (len(land), len(stops), len(town_list), len(areas)))
    print("   map area %.1f x %.1f pt" % (mx1 - mx0, my1 - my0))
    span_km = (la1 - la0) * 111.0
    outside = [n[0] for n in dropped["regions"] + dropped["waters"]] +               [n for n, _lat, _lng in dropped["areas"]
               if not inside(*pt(_lng, _lat), pad=0)]
    if outside:
        print("   decorative labels needing repositioning for this frame: %s"
              % ", ".join(outside))
    print("   about %.0f km tall -> 1 pt = %.0f m (symbols are NOT drawn to this scale)"
          % (span_km, span_km * 1000 / (my1 - my0)))


if __name__ == "__main__":
    main()
