/* Approximate modern anchors, researched 2026-09-09. Not an exhaustive or verified travel log.
   Regional anchors must never be presented as exact historical landfalls. */
window.NORSE_SOURCES = {
  leifMuseum: ['Eiríksstaðir Museum · the two Vinland sagas', 'https://www.eiriksstadir.is/the-sagas'],
  leifCanada: ['Newfoundland & Labrador Heritage · Norse voyages', 'https://www.heritage.nf.ca/articles/exploration/norse-north-atlantic.php'],
  meadows: ['Parks Canada · L’Anse aux Meadows', 'https://parks.canada.ca/culture/designation/lieu-site/anse-aux-meadows'],
  leifNidaros: ['Viking Network · Leif and Nidaros', 'https://www.viking.no/nb/vikingenes-konger-og-jarler/leif-erikson-leifur-eiriksson/'],
  leifBio: ['Dictionary of Canadian Biography · Leif', 'https://www.biographi.ca/en/bio/leifr_eiriksson_1F.html'],
  rolloStudy: ['Henry Project · Rollo and disputed origins', 'https://fasg.org/projects/henryproject/data/rollo000.htm'],
  rolloHistory: ['World History Encyclopedia · Rollo', 'https://www.worldhistory.org/Rollo_of_Normandy/'],
  rolloNormandy: ['Normandy Tourism · Rollo’s Normandy', 'https://www.normandie-tourisme.fr/rollon-duc-de-normandie/'],
  rolloWalcheren: ['DBNL · later history citing Dudo on Walcheren', 'https://www.dbnl.org/tekst/wage004vade02_01/wage004vade02_01_0025.php'],
  rolloSaga: ['Heimskringla · Harald Fairhair’s saga, Rolf’s exile', 'https://www.gutenberg.org/files/598/598-h/598-h.htm'],
  williamNormandy: ['Caen Tourism · William, his Norman roots and descendants', 'https://www.caenlamer-tourisme.fr/decouvrir-caen-la-mer/caen-une-ville-aux-mille-facettes/histoire-de-guillaume-le-conquerant/'],
  williamPevensey: ['English Heritage · Pevensey and the invasion', 'https://www.english-heritage.org.uk/visit/places/pevensey-castle/history/'],
  williamBattle: ['Historic England · Battle of Hastings', 'https://historicengland.org.uk/listing/the-list/list-entry/1000013'],
  williamWestminster: ['Westminster Abbey · William’s coronation', 'https://www.westminster-abbey.org/abbey-commemorations/royals/william-i-the-conqueror'],
  richardRoyal: ['Royal Household · Richard the Lionheart', 'https://www.royal.uk/richard-i'],
  richardNormandy: ['Normandy Tourism · Richard’s ancestry and Château Gaillard', 'https://en.normandie-tourisme.fr/discover/medieval-normandy/leading-figures/richard-the-lionheart/'],
  richardAustria: ['Danube Tourism · Richard’s Dürnstein trail', 'https://www.donau.com/en/excursions/themenweg-richard-loewenherz'],
  richardCyprus: ['Visit Cyprus · Limassol wedding tradition', 'https://www.visitcyprus.com/discover-cyprus/culture/sites-and-monuments/lemesos-limassol-medieval-castle/'],
  audSaga: ['Laxdæla saga · chapters 1–6', 'https://sagadb.org/laxdaela_saga.en#1'],
  audLife: ['Shetland.org · Aud’s life and journey', 'https://www.shetland.org/blog/aud-the-deep-minded'],
  audHvammur: ['Visit West Iceland · Hvammur in Dalir', 'https://www.west.is/en/experiences/culture-heritage/history-and-culture/hvammur'],
  audCross: ['Visit West Iceland · Krosshólaborg tradition and location', 'https://www.west.is/is/stadir/krossholaborg'],
  haraldCambridge: ['Cambridge · Harald in Byzantine service', 'https://www.cambridge.org/core/books/abs/varangians-of-byzantium/haraldr-sigurarson-and-his-period-as-a-varangian-in-constantinople-10341043/C13D204FFE93C484F561A6BEA41990FD'],
  haraldMuseum: ['Viking Ship Museum · Harald Hardrada', 'https://www.vikingeskibsmuseet.dk/en/professions/education/viking-age-people/historical-characters/harald-hardrada-of-norway'],
  haraldSaga: ['Heimskringla · Saga of Harald Hardrade (later narrative)', 'https://www.gutenberg.org/files/598/598-h/598-h.htm'],
  haraldEast: ['Harald’s saga · eastern journey and Holy Land', 'https://www.gutenberg.org/files/22093/22093-h/22093-h.htm'],
  haraldStudy: ['Balcanica Posnaniensia · Harald’s Sicilian service', 'https://pressto.amu.edu.pl/index.php/bp/article/view/53087'],
  haraldBio: ['Harald Hardrada · biography and source bibliography', 'https://en.wikipedia.org/wiki/Harald_Hardrada']
};
window.NORSE_PEOPLE = [
  {id:'leif',name:'Leif Erikson',short:'Leif',theme:'Across the Atlantic',color:'#216580',note:'Homes, saga voyages and candidate American landfalls. Helluland and Markland are regions with debated boundaries; Vinland has no single agreed pin.'},
  {id:'rollo',name:'Rollo & descendants',short:'Family',theme:'Rollo · William · Richard',color:'#a2562d',note:'One family-history trip: mix Rollo, William the Conqueror and Richard the Lionheart in the aunt’s visit order. William and Richard belong to the later Norman and Angevin legacy. Rollo’s origins remain disputed.'},
  {id:'aud',name:'Aud the Deep-Minded',short:'Aud',theme:'Islands & a new home',color:'#6d528b',note:'Also called Auðr, Unn or Unnr. Much of her story comes from later sagas. Regional anchors keep unnamed ports and uncertain Icelandic sites visibly approximate.'},
  {id:'harald',name:'Harald Hardrada',short:'Harald',theme:'Eastward & back again',color:'#467444',note:'Early exile, Byzantine service, Scandinavian reign and England. Broad campaign regions are included without inventing precise battle sites or unnamed towns.'}
];
// id, person, name, latitude, longitude, evidence, location precision, connection, source key
window.NORSE_STOPS = [
  ['l-eiriksstadir','leif','Eiríksstaðir · Iceland',65.06,-21.55,'uncertain','Site vicinity','Probable birthplace; family farm association.','leifMuseum'],
  ['l-brattahlid','leif','Brattahlíð / Qassiarsuk · Greenland',61.16,-45.51,'saga','Settlement vicinity','Family home and Greenland base in the saga tradition.','leifBio'],
  ['l-hebrides','leif','Hebrides · Scotland',57.6,-7.1,'saga','Regional anchor','Weather-driven stop in Eiríks saga; island unspecified.','leifMuseum'],
  ['l-nidaros','leif','Nidaros / Trondheim · Norway',63.43,10.4,'saga','City anchor','Visit to Olaf Tryggvason’s court.','leifNidaros'],
  ['l-helluland','leif','Helluland candidate · Baffin Island',65.2,-64,'uncertain','Regional anchor','Rocky saga land, usually associated with Baffin Island; exact landfall unknown.','leifCanada'],
  ['l-markland','leif','Markland candidate · Labrador',54.5,-57.5,'uncertain','Regional anchor','Wooded saga land, commonly associated with Labrador; exact landfall unknown.','leifCanada'],
  ['l-meadows','leif','L’Anse aux Meadows · Newfoundland',51.595,-55.533,'uncertain','Archaeological site','Confirmed Norse settlement; Leif’s personal association remains uncertain. Research anchor for Vinland.','meadows'],
  ['r-more','rollo','Møre · Norway',62.6,6.7,'uncertain','Regional anchor','Norwegian origin tradition depends on identifying Rollo with Göngu-Hrólfr.','rolloStudy'],
  ['r-denmark','rollo','Denmark · alternative origin',56,9.5,'uncertain','Country anchor','Dudo gives a Danish origin; no secure hometown. Alternative to Møre.','rolloStudy'],
  ['r-hebrides','rollo','Hebrides · Scotland',57.6,-7.1,'uncertain','Regional anchor','Western-isles exile belongs to the disputed Göngu-Hrólfr tradition.','rolloSaga'],
  ['r-england','rollo','England · early travel tradition',52.2,0.4,'uncertain','Regional anchor','Dudo describes English contacts; pin is a broad eastern-England anchor, not a known port.','rolloHistory'],
  ['r-walcheren','rollo','Walcheren · Netherlands',51.53,3.55,'uncertain','Island anchor','Early voyage association in later Norman narrative; identity and chronology are disputed.','rolloWalcheren'],
  ['r-rouen','rollo','Rouen · Normandy',49.443,1.099,'supported','City anchor','Core of his power and the territory granted around 911.','rolloStudy'],
  ['r-bayeux','rollo','Bayeux · Normandy',49.277,-0.703,'saga','City anchor','Later accounts link his campaigns and Poppa to Bayeux.','rolloHistory'],
  ['r-paris','rollo','Paris · France',48.857,2.352,'uncertain','City anchor','Siege associations appear in later accounts; his individual role is uncertain.','rolloHistory'],
  ['r-chartres','rollo','Chartres · France',48.447,1.488,'supported','City anchor','Campaign and defeat associated with the 911 settlement.','rolloHistory'],
  ['r-epte','rollo','Saint-Clair-sur-Epte · France',49.207,1.682,'supported','Village anchor','Traditional site of the agreement that established his Norman territory.','rolloNormandy'],
  ['r-roumare','rollo','Roumare forest · Normandy',49.413,0.965,'context','Forest anchor','Local naming legend; useful research stop, not an established visit.','rolloNormandy'],
  ['w-falaise','rollo','Falaise · Normandy',48.893,-0.2,'supported','Town / castle vicinity','Birthplace and childhood setting.','williamNormandy','William the Conqueror'],
  ['w-caen','rollo','Caen · Normandy',49.183,-0.369,'supported','City anchor','Ducal centre, castle and abbey foundations; burial at the Abbaye aux Hommes.','williamNormandy','William the Conqueror'],
  ['w-dives','rollo','Dives estuary · Normandy',49.286,-0.101,'supported','Estuary anchor','Fleet preparations for the invasion of England; approximate harbour area.','williamNormandy','William the Conqueror'],
  ['w-pevensey','rollo','Pevensey · England',50.82,0.338,'supported','Castle / landing vicinity','Landing and initial fortified base in 1066; historic shoreline differed.','williamPevensey','William the Conqueror'],
  ['w-hastings','rollo','Hastings · England',50.856,0.584,'supported','Town anchor','Invasion base after Pevensey; distinct from the battlefield at Battle.','williamBattle','William the Conqueror'],
  ['w-battle','rollo','Battle · Hastings battlefield',50.914,0.487,'supported','Battlefield vicinity','Victory over Harold; later abbey commemorates the battle.','williamBattle','William the Conqueror'],
  ['w-westminster','rollo','Westminster · London',51.499,-0.128,'supported','Abbey vicinity','Coronation as king of England in 1066.','williamWestminster','William the Conqueror'],
  ['rl-limassol','rollo','Limassol · Cyprus',34.671,33.041,'uncertain','Old-town / castle vicinity','Marriage to Berengaria in Limassol; the castle is the traditional location, not a proven exact venue.','richardCyprus','Richard the Lionheart'],
  ['rl-acre','rollo','Acre / Akko',32.923,35.069,'supported','City anchor','Third Crusade siege and capture; approximate city anchor.','richardRoyal','Richard the Lionheart'],
  ['rl-arsuf','rollo','Arsuf / Apollonia',32.193,34.806,'supported','Coastal / battlefield vicinity','Crusade battle; pin is an approximate coastal anchor.','richardRoyal','Richard the Lionheart'],
  ['rl-jaffa','rollo','Jaffa',32.052,34.752,'supported','Old-city anchor','Fighting and the peace agreement associated with the end of his crusade.','richardRoyal','Richard the Lionheart'],
  ['rl-durnstein','rollo','Dürnstein · Austria',48.395,15.52,'supported','Town / castle vicinity','Captivity association and modern Richard the Lionheart history trail.','richardAustria','Richard the Lionheart'],
  ['rl-winchester','rollo','Winchester · England',51.06,-1.313,'supported','City / cathedral vicinity','Recoronation after his release in 1194.','richardRoyal','Richard the Lionheart'],
  ['rl-gaillard','rollo','Château Gaillard · Les Andelys',49.239,1.403,'supported','Castle vicinity','Fortress built under Richard to defend Normandy.','richardNormandy','Richard the Lionheart'],
  ['rl-chalus','rollo','Châlus · France',45.655,0.981,'supported','Town / castle vicinity','Final siege and death in 1199.','richardRoyal','Richard the Lionheart'],
  ['a-raumsdal','aud','Romsdal · Norway',62.57,7.69,'saga','Regional anchor','Her father’s home region in Laxdæla saga.','audSaga'],
  ['a-dublin','aud','Dublin · Ireland',53.349,-6.26,'saga','City anchor','Marriage and family association with Olaf the White.','audLife'],
  ['a-hebrides','aud','Hebrides · Scotland',57.6,-7.1,'saga','Regional anchor','Family’s western-isles background; exact residence unspecified.','audLife'],
  ['a-caithness','aud','Caithness · Scotland',58.42,-3.35,'saga','Regional anchor','Departure after her son’s death; secret shipbuilding story.','audSaga'],
  ['a-orkney','aud','Orkney · Scotland',59,-3,'saga','Island-group anchor','Stop during migration; granddaughter married here.','audSaga'],
  ['a-faroes','aud','Faroe Islands',62,-6.85,'saga','Island-group anchor','Another granddaughter’s marriage during the journey.','audSaga'],
  ['a-vik','aud','Vikrarskeið · southern Iceland',63.42,-19,'uncertain','Regional anchor','Saga shipwreck; broad south-coast anchor, exact historical site uncertain.','audSaga'],
  ['a-esjuberg','aud','Esjuberg / Kjalarnes · Iceland',64.23,-21.8,'saga','District anchor','Visit to her brother Helgi, whose offer she rejected.','audSaga'],
  ['a-bjarnarhofn','aud','Bjarnarhöfn · Iceland',64.998,-22.967,'saga','Settlement vicinity','Winter with her brother Bjorn.','audSaga'],
  ['a-dogurdarnes','aud','Dögurðarnes / Dagverðarnes · Iceland',65.17,-22.52,'uncertain','Modern locality anchor','Saga midday meal stop; modern locality represents the peninsula, not an exact landing.','audSaga'],
  ['a-kambsnes','aud','Kambsnes · Hvammsfjörður',65.081,-21.803,'uncertain','Modern locality anchor','Saga stop associated with losing a comb; local farm anchor, not exact landing.','audSaga'],
  ['a-hvammur','aud','Hvammur · Dalir, Iceland',65.2185,-21.8287,'supported','Settlement vicinity','Her settlement, identified in local heritage interpretation.','audHvammur'],
  ['a-krossholar','aud','Krosshólaborg / Krosshólar · Iceland',65.2162,-21.7895,'saga','Heritage-site anchor','Traditional prayer site; modern memorial near Hvammur.','audCross'],
  ['h-ringerike','harald','Ringerike · Norway',60.1,10.2,'supported','Regional anchor','Birth and family region; no exact birthplace asserted.','haraldBio'],
  ['h-stiklestad','harald','Stiklestad · Norway',63.797,11.558,'supported','Site vicinity','Defeat in 1030 before his eastern exile.','haraldCambridge'],
  ['h-sweden','harald','Sweden · exile route',59.5,15,'supported','Country / route anchor','Passage east; no specific town asserted.','haraldCambridge'],
  ['h-novgorod','harald','Holmgard / Novgorod',58.522,31.275,'saga','City anchor','Saga’s Rus’ setting; distinguish it from historical Kyiv connections.','haraldEast'],
  ['h-kyiv','harald','Kyiv · Ukraine',50.45,30.523,'supported','City anchor','Service with Yaroslav and later marriage to Elisiv.','haraldCambridge'],
  ['h-constantinople','harald','Constantinople / Istanbul',41.008,28.978,'supported','City anchor','Byzantine imperial service.','haraldCambridge'],
  ['h-anatolia','harald','Asia Minor · Anatolia',39,32,'supported','Regional anchor','Broad military-service region; not a specific battle site.','haraldMuseum'],
  ['h-sicily','harald','Sicily · Italy',37.6,14.2,'supported','Island anchor','Service in the Byzantine Sicilian campaign.','haraldStudy'],
  ['h-bulgaria','harald','Bulgaria · campaign region',42.7,25.3,'supported','Regional anchor','Participation in suppressing Peter Deljan’s uprising; approximate regional pin.','haraldStudy'],
  ['h-jerusalem','harald','Jerusalem',31.778,35.235,'saga','City anchor','Holy Land journey reported in his saga.','haraldEast'],
  ['h-jordan','harald','River Jordan · pilgrimage tradition',31.837,35.546,'saga','River-region anchor','Saga bathing episode; exact location unspecified.','haraldEast'],
  ['h-ladoga','harald','Aldeigjuborg / Staraya Ladoga',59.998,32.295,'saga','Settlement vicinity','Saga stop to obtain a ship on the return west.','haraldSaga'],
  ['h-sigtuna','harald','Sigtuna · Sweden',59.617,17.723,'saga','Town anchor','Swedish stop in the return narrative.','haraldSaga'],
  ['h-oslo','harald','Oslo · Norway',59.908,10.767,'supported','City anchor','Royal base; traditional founding association, though settlement is older.','haraldBio'],
  ['h-nidaros','harald','Nidaros / Trondheim · Norway',63.43,10.4,'supported','City anchor','Royal activity and later burial of his remains.','haraldBio'],
  ['h-hedeby','harald','Hedeby · present-day Germany',54.491,9.566,'supported','Site vicinity','Attack during his wars with Denmark.','haraldBio'],
  ['h-nisa','harald','Nissan estuary · Sweden',56.655,12.855,'supported','Coastal anchor','Battle of Niså against Sweyn; offshore position approximate.','haraldBio'],
  ['h-solund','harald','Solund / Sognefjord mouth · Norway',61.07,4.85,'saga','Island-group anchor','Fleet assembly before the England expedition.','haraldSaga'],
  ['h-shetland','harald','Shetland · Scotland',60.2,-1.25,'saga','Island-group anchor','Stop on the 1066 expedition.','haraldSaga'],
  ['h-orkney','harald','Orkney · Scotland',59,-3,'supported','Island-group anchor','Gathered forces en route to England.','haraldBio'],
  ['h-scarborough','harald','Scarborough · England',54.282,-0.4,'uncertain','Town anchor','Saga attack story; its historical reliability is debated.','haraldBio'],
  ['h-holderness','harald','Holderness · England',53.85,-0.08,'saga','Regional anchor','Coastal campaign in the invasion narrative.','haraldSaga'],
  ['h-riccall','harald','Riccall · England',53.834,-1.059,'supported','Village / river vicinity','Fleet base on the Ouse; exact anchorage is approximate.','haraldBio'],
  ['h-fulford','harald','Fulford · England',53.932,-1.073,'supported','Battlefield vicinity','Victory before Stamford Bridge.','haraldBio'],
  ['h-york','harald','York · England',53.96,-1.087,'supported','City anchor','Submission after Fulford.','haraldBio'],
  ['h-stamford','harald','Stamford Bridge · England',53.99,-0.913,'supported','Village / battlefield vicinity','Final battle and death in 1066.','haraldBio']
].map(([id,person,name,lat,lng,evidence,precision,note,source,figure])=>({id,person,name,lat,lng,evidence,precision,note,source,figure:figure||(person==='rollo'?'Rollo':window.NORSE_PEOPLE.find(p=>p.id===person).name)}));
