"""Convert the Aurora DXF into a compact, layer-preserving browser SVG.

Requires ezdxf: ``py -m pip install ezdxf``
Run from the repository root with no arguments.
"""

from pathlib import Path
import html
import re

import ezdxf
from ezdxf import bbox
from ezdxf.path import make_path


HERE = Path(__file__).resolve().parent
SOURCE = HERE / "SpaceStationAurora.dxf"
OUTPUT = HERE / "Station_Aurora_Vector.svg"
SVG_WIDTH = 792

LAYER_COLORS = {
    "0": "#a9c6d3",
    "A.Engines": "#ff6b58",
    "C.Bridge": "#70d8ff",
    "D.Science": "#70d8ff",
    "E.Hydroponics": "#69d6b0",
    "E2.Hydroponics Outlines": "#69d6b0",
    "F.Hub": "#d9edf4",
    "G.Crew Quarter": "#8ecbff",
    "H.Kitchen": "#8ecbff",
    "I.Storage": "#c4d5dc",
    "J.Engineering": "#ffad66",
    "K.Power": "#ff6b58",
    "L.Shuttles": "#ffad66",
    "L1.Shuttle Outlines": "#ffad66",
    "M.Radiators": "#789eff",
    "N.SolarArrays": "#e5c85c",
    "Z.Box": "#d5e0e4",
}


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def number(value: float) -> str:
    return f"{value:.2f}".rstrip("0").rstrip(".")


def main() -> None:
    document = ezdxf.readfile(SOURCE)
    modelspace = document.modelspace()
    drawing_bounds = bbox.extents(modelspace, fast=False)
    minimum, maximum = drawing_bounds.extmin, drawing_bounds.extmax
    scale = SVG_WIDTH / (maximum.x - minimum.x)
    svg_height = round((maximum.y - minimum.y) * scale)

    def point(vertex) -> str:
        x = (vertex.x - minimum.x) * scale
        y = (maximum.y - vertex.y) * scale
        return f"{number(x)} {number(y)}"

    groups = []
    for layer in document.layers:
        name = layer.dxf.name
        entities = [entity for entity in modelspace if entity.dxf.layer == name]
        commands = []
        for entity in entities:
            try:
                path = make_path(entity)
                vertices = list(path.flattening(distance=0.35, segments=8))
            except (TypeError, ValueError, AttributeError):
                continue
            if not vertices:
                continue
            commands.append("M" + point(vertices[0]))
            commands.extend("L" + point(vertex) for vertex in vertices[1:])
            if path.is_closed:
                commands.append("Z")
        if not commands:
            continue
        color = LAYER_COLORS.get(name, "#a9c6d3")
        escaped_name = html.escape(name, quote=True)
        groups.append(
            f'  <g id="layer-{slug(name)}" data-layer="{escaped_name}" '
            f'stroke="{color}"><path d="{" ".join(commands)}"/></g>'
        )

    output = "\n".join(
        [
            '<?xml version="1.0" encoding="UTF-8"?>',
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SVG_WIDTH} {svg_height}" '
            'role="img" aria-labelledby="title description">',
            "  <title id=\"title\">Space Station Aurora vector blueprint</title>",
            "  <desc id=\"description\">Layer-preserving vector conversion of the supplied DXF drawing.</desc>",
            "  <metadata>Source: SpaceStationAurora.dxf; generated by convert_dxf_to_svg.py</metadata>",
            "  <g fill=\"none\" stroke-width=\"0.9\" stroke-linecap=\"round\" "
            'stroke-linejoin="round" vector-effect="non-scaling-stroke">',
            *groups,
            "  </g>",
            "</svg>",
            "",
        ]
    )
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT} ({SVG_WIDTH} x {svg_height}, {len(groups)} layers)")


if __name__ == "__main__":
    main()
