"""Full adopted design content, embedded in the single review brainstorm page."""
from review_content import PERCH_FLIGHTS

APPROVED = '''
<div class="callout"><strong>Approved by the user · 22 September 2026.</strong> G7 uses coin values and an upside-down tally. G8 keeps HRAFN and adds the five-perch conversion to a four-digit lock. These replace weighing and the cryptex. The remaining review recommendations retain their own proposal status.</div>
<div class="grid">
<article class="card" id="approved-coins"><span class="pill">RV-20 · Approved mechanism</span><h2>The treasure tally</h2>
<p><strong>Select coins → add their values → display 3705 → rotate → SOLE.</strong></p>
<ol><li>The mark on the coin cache selects the matching coins from the mixed hoard. Keep this separate from the denomination/value mark.</li><li>A merchant’s key supplies each denomination’s fictional game value. Count and add only the selected coins; their total must be exactly <strong>3705</strong>.</li><li>Record the total on the supplied calculator or four-wheel tally, labelled <em>“Use this to tally treasure.”</em></li><li>A3 tells players to turn the whole display upside down. Calculator-style 5, 0, 7, 3 read left-to-right as S, O, L, E after rotation.</li><li><strong>SOLE</strong> opens G7 and releases the initial Harald materials, including the perch card.</li></ol>
<p>No grams, weighing, decimal point, rounding or discarded digit. Preserve the physical sorting and word-reveal moment.</p>
<h3>Two supported tally choices</h3><ul><li><strong>Calculator:</strong> lowest-build prototype. Check the actual shapes of 3, 7 and 5 and whether 3705 remains displayed when handled. Label its job; test reset/power.</li><li><strong>3D-printed tally:</strong> four independently settable 0–9 wheels with one clear reading window. Players do the addition and set the result manually; it is not an adding machine. Use suitable segmented numerals and stable wheel positions so rotating the whole prop does not alter the digits. Reset to 0000.</li></ul>
<p class="notice"><strong>Still open:</strong> calculator versus wheels (PR-24); coin quantities, fictional values, selection mark and denomination marks (PR-25). No coin set or physical display is claimed tested. The total and answer are approved; the physical implementation is unfinished.</p>
</article>
<article class="card" id="approved-perches"><span class="pill">RV-21 · Approved mechanism</span><h2>The raven’s flights</h2>
<p><strong>Decode HRAFN → visit H–R–A–F–N → read 2–6–4–8.</strong></p>
<p>Keep H5’s underlined RAVEN selector, H4’s branch-rune key and the corrected Harald map. The five decoded letters identify five visits among eight possible perches: <strong>H, R, T, O, A, N, F, S</strong>.</p>
<ol><li>Start at H, then follow the direct drawn connection to R.</li><li>Continue directly R→A, A→F and F→N, using the decoded letter order.</li><li>Read one number per connection, in flight order: <strong>2648</strong>. Do not add numbers, count line lengths, translate HRAFN or find a shortest route.</li><li>Use <strong>one four-digit lock directly on the board-kit pouch</strong>. It contains H1, the ticket, board, pieces and challenge rules.</li></ol>
<h3>Player-facing card</h3><p>Working size: one half-Letter sheet, 8.5×5.5 inches, subject to print-size proof. Title: <em>“The raven’s flights.”</em> Clue: <em>“Follow the five letters you uncovered. Read the number on each flight, in order.”</em> Four blank answer boxes. All connections look alike; directions come from the letters. No route highlight, HRAFN or answer on the player copy.</p>
<p><strong>Release:</strong> inside G7 with H4/H5 and Harald’s map, outside the G8 board pouch. Match the perch card and pouch with a small raven emblem so the four digits have an obvious destination. The card is an extra prop, not another postcard.</p>
<p class="notice">The code and pictured network are adopted. Final printable artwork and its physical test remain open (PR-26). Existing cryptex, key and keyed-closure proposals are superseded. The number of puzzle gates stays eleven in the review flow.</p>
</article></div>
<figure><a href="../output/visualizations/norse-five-perches-comparison.png" target="_blank" rel="noopener"><img src="../output/visualizations/norse-five-perches-comparison.png" alt="Accepted five-perch concept: unmarked player card beside the highlighted HRAFN route giving 2648" loading="lazy"></a><figcaption>Accepted mechanism sketch. Left: player layout. Right: designer answer overlay. This comparison image contains the answer and must not be packed in the game. The final player print file is not yet produced.</figcaption></figure>
<details><summary>Exact perch connections — production reference</summary><div><p>Every connection is two-way and carries one digit. The network has no line crossings. Only the decoded letter order selects the route.</p><div class="tablewrap"><table><thead><tr><th>Connection</th><th>Digit</th><th>Role</th></tr></thead><tbody>
'''+''.join(f'<tr><td>{a}–{b}</td><td>{n}</td><td>{"Selected by HRAFN" if i<4 else "Other possible flight"}</td></tr>' for i,(a,b,n) in enumerate(PERCH_FLIGHTS))+'''
</tbody></table></div></div></details>
<h2 id="postcard-changes">Postcards and supporting print changes</h2>
<p><strong>A1 requires a change; A3 needs a small wording update. H4 and H5 can remain as printed.</strong> The copy below is a draft for the next print pass, not a claim that the PDFs or gallery backs have been regenerated. Preserve the historical paragraphs, stamps, family marks, Fun Facts and itinerary evidence.</p>
<div class="tablewrap"><table><thead><tr><th>Item</th><th>Change</th><th>Release / status</th></tr></thead><tbody>
<tr><td>A1 · Dogurdarnes</td><td>Replace only the weighing paragraph with the value-tally instruction below.</td><td>G6 cache; PDF and back image still old.</td></tr>
<tr><td>A3 · Esjuberg</td><td>Replace the “reading” paragraph with the treasure-tally wording below; keep the flip discovery.</td><td>G6 cache; PDF and back image still old.</td></tr>
<tr><td>H4 · Hedeby</td><td>No required change. Its key still decodes HRAFN. Preserve the Mediterranean travel-order clue.</td><td>G7.</td></tr>
<tr><td>H5 · Sicily</td><td>No required change. Keep the underlined RAVEN selector.</td><td>G7.</td></tr>
<tr><td>New perch card</td><td>Use the accepted graph, player clue and four answer boxes. Do not print the solution view.</td><td>G7; player print file pending.</td></tr>
<tr><td>Coin key, cache and tally</td><td>Supply a fictional value key, matching selection marks and labelled tally device.</td><td>G6; design/build pending.</td></tr>
<tr><td>Old balance cue slip</td><td>Superseded. Do not pack the scale/truncation slip from the earlier six-slip PDF. Replacement draft is below.</td><td>G6; revised printable slip pending.</td></tr>
<tr><td>Hint companion</td><td>G7 explains adding and rotating; G8 now explains HRAFN→flights→2648.</td><td>Updated with this brainstorm.</td></tr>
</tbody></table></div>
<div class="grid"><article class="card"><h3>A1 · replacement puzzle paragraph</h3><blockquote>The mark on the cache tells you which coins to keep. Use the merchant’s values to add up their worth, then record the total on the treasure tally.</blockquote><p class="small">Replaces “Whatever pile the map marks for you, weigh it before anything else. Don’t guess the number — read it.”</p></article>
<article class="card"><h3>A3 · replacement puzzle paragraph</h3><blockquote>One more thing about your treasure tally from Dogurdarnes: turn the whole thing upside down. There’s a word hiding in those numbers.</blockquote><p class="small">Replaces the second paragraph’s reference to “that reading”; retains A3’s upside-down action.</p></article></div>
<article class="card"><h3>Optional playtest cue · Counting the treasure</h3><blockquote>Match the cache mark to the coins. Use the merchant’s key to add the value of every matching coin. Record the whole-number total on the treasure tally. Keep your tally beside Liv’s postcards.</blockquote><p>Keep the flip instruction on A3. This cue supports the prototype if the draft A1 has not yet been printed; it must replace the old balance cue.</p></article>
<h3>Check before printing or packing</h3><ul><li>Independently total the selected coin set to 3705; check selection and value marks are distinguishable. Coins are fictional game currency, not a historical-value claim.</li><li>Show the actual rotated tally to someone unfamiliar with SOLE. Check wheel stability or calculator display, and that the word lock supports S–O–L–E.</li><li>From the corrected rune map and current H4/H5, decode HRAFN and follow only direct flights to get 2648. Check readability at final card size without an answer key.</li><li>Verify that the perch card is accessible before the board lock and that G8 directly secures the complete board kit. Keep H1 inside G8 and H6 inside G10.</li><li>Rebuild both A1/A3 print formats and their gallery back images together when the copy goes to print. Recheck preserved finale clues and keep the deck count unchanged.</li></ul>
<details><summary>Superseded mechanism history</summary><div><p><strong>G7:</strong> weighing to 370.56 g, truncating to 370.5 and deleting the decimal point is retired. No scale or calibration is required by the approved tally version.</p><p><strong>G8:</strong> HRAFN as the setting on a five-letter cryptex, followed by a key to a second board-kit closure, is retired. HRAFN now selects four flight digits and G8 is one direct four-digit lock.</p><p>Original puzzle snapshots and old PDFs remain available as historical source material. They do not override these approved replacements.</p></div></details>
'''
