"""Review evidence and proposals, with explicitly approved G7/G8 updates."""

# Approved five-perch conversion; the print artwork still needs a physical proof.
PERCH_ROUTE = 'HRAFN'
PERCH_FLIGHTS = [('H','R',2),('R','A',6),('A','F',4),('F','N',8),
                 ('H','O',7),('O','F',3),('F','S',9),('S','N',5),
                 ('N','T',1),('T','R',8),('O','A',5),('A','N',3)]
PERCH_CODE = '2648'
FINDINGS = [
('RV-01','Blocker','No complete packing and release plan','ST-01 / PC-18',
 'The current puzzle data still says “Open” for several releases. Its displayed sequence puts the board before the runes while its own description says the reverse. A list of good puzzles is not yet an executable game.',
 'Use the proposed Adventure flow below: every card has a first release, every gate has contents, and two parallel branches have explicit joins. Treat this as a packing proposal, not a claim about the existing bag.'),
('RV-02','Blocker','One lock cannot hold several future answers','PZ-03 / comb / PZ-20',
 'SOLE, candidate BOOK and MEAD are assigned to the owned four-letter lock. Resetting it between these puzzles requires intervention or exposes future combinations. The user confirms some 3-digit, 4-digit and 4-letter locks, but not quantities or dial alphabets.',
 'Use distinct locks for SOLE and MEAD in the recommended version; park the BOOK gate. Check that each physical dial can spell its assigned word. Inventory before buying. Never depend on a host resetting a lock mid-game.'),
('RV-03','Blocker','RAVEN selects two possible fourth letters','PZ-02 / PZ-09',
 'The printed Harald grid has a real F at E3 and a decoy L at E7. Both are in E, one of the columns selected by RAVEN. The printed clue therefore permits HRAFN and HRALN; recognizing an Old Norse word is not an adequate rule.',
 'The separate review map moves only the E7 decoy to I7. R, A, V, E and N now each contain one stem. The route geometry and board back are preserved. Physical legibility is still untested.'),
('RV-04','Blocker','The board ticket teaches different rules from the puzzle','PZ-01 / PZ-07',
 'The ticket explains moving all pieces and capturing. The unique 253 route was computed with every piece except the king fixed and no capture. H1 asks for three moves but never states those restrictions.',
 'Add the supplied “Our three-move challenge” slip, or merge it into H1 later. State fixed pieces, no capture/jumping, exactly three rook moves, any corner, and distances excluding the starting square. The 11×11 fixed-board search independently confirms F6 → H6 → H11 → K11.'),
('RV-05','Blocker','Coin tally approved; selector and values still need completing','PZ-03 / PR-02 / PR-20 / RV-20',
 'The existing A1 PDF still instructs weighing, and A3 refers to a reading. That mechanism is superseded by the approved value-summing puzzle. No final coin inventory, selection mark or value key has been produced.',
 'Select the coins by a matching cache mark, add their fictional game values to exactly 3705, display the total on a calculator or four-wheel tally, then rotate the whole display 180 degrees to read SOLE. No decimal or discarded digit. Complete and test the coin set, value key, selection marks and display; draft A1/A3 changes are in Approved changes.'),
('RV-06','Blocker','BOOK has no verified extraction','PC-06 / PR-19',
 'AD exists, contrary to one stale risk note, but no matched comb tooth layout, alignment stops or exact extracted letters were found. The answer BOOK is still a candidate, not a working prop.',
 'Keep AD in the deck for the final filter. Make the comb an optional exploration until a real-size mask cleanly reveals only B–O–O–K. If it becomes mandatory later, add its own lock and a reliable placement/orientation cue.'),
('RV-07','Blocker','The ruler puzzle has no calibrated answer','PZ-14 / PC-15',
 'CROSSBOW BOLT, TREATY and SCALE 1 TO 5 identify a method, but the physical ruler, exact endpoints, unit, rounding convention and lock digit count are unresolved. A rescaled print changes the answer. “Tree + tea” also admits several readings.',
 'Retain the three cards and rebuses as an optional discovery in the 60–90-minute version. Do not assign a numeric code. To restore a lock: choose the actual ruler, mark two measurement centres, add a scale check and units/rounding rule, then independently measure the final laminated sheet.'),
('RV-08','Fix before testing','Top-edge action is not discoverable from the messages','PC-06 / PC-13',
 'L2 and L3 contain no instruction to combine them, reverse one, or use transmitted light. The proof image and top-edge test PDF do not establish reliable viewing through two finished, double-sided cards.',
 'Use the supplied “Two skies” cue for the first playtest. Test actual stock, trimming, ink, light source and laminate. The current 1576 is an intended result; do not call this gate ready until strangers can see it. A sealed rescue answer can keep a prototype running, but is not a production fix.'),
('RV-09','Fix before testing','Aud’s printed wording is weaker than its documented explanation','PZ-17',
 'The puzzle description says A2 gives a southward direction and a forest cue. The current PDF gives the forest cue only, and says “rivers, fords and gates” while the ticket asks for bridges, fords and gates. The ticket itself is a good six-leg tally with a worked first row.',
 'Proposed A2 replacement: “From the standing stone I went south, along the road beside the forest, to the village at the crossing. I might have to remember how many bridges, fords and gates I crossed.” Validate this against the actual drawn route before reprinting. Preserve the tally 5 / 2 / 1 only if the paper walkthrough agrees.'),
('RV-10','Fix before testing','Final digits are asserted, not geometrically proved','PZ-06 / PZ-18',
 'The original answer PDFs label the shapes 1, 9, 7, 2. Those labels and the solver’s fixed digit table do not test recognition. Harald is an angular zigzag; Rollo’s loop nearly closes near Rouen/Roumare; Leif’s short opening stroke is small. Aud’s seven has a nearly vertical stem.',
 'Run a blind recognition test with labels hidden, north up and no expected code given. If a shape fails, adjust a schematic inset or route design in a new proposal, then recheck all dependent clues. Do not rely on guessing the year 1972. The review does not silently warp geography or claim these shapes passed.'),
('RV-11','Blocker for self-guided play','The existing hint site is incomplete and stale','norse-hints.html',
 'Only the opening, beasts, top edge, finale and ending are listed. The finale still tells players to sort interleaved postcard dates, which the current cards do not carry. The top-edge entry exposes design notes rather than a gradual hint.',
 'A separate review hint page now covers all 11 proposed gates, with three hints and an explicitly hidden solution each. Supply a reachable local/hosted URL or printed fallback; a localhost link on the designer’s computer is not automatically usable by players’ phones. Test it without a host.'),
('RV-12','Fix before testing','The journal makes the decoys contradict the story','PZ-18 / journal PDF',
 '“Every place I actually stopped” excludes four postcards that describe real visits; the Walcheren transition ticket and journal then use one of those visits as an ordering anchor. Literally discarding that card makes the chain harder to follow.',
 'The proposed journal says these are stops selected for the traced routes; other cards remain travel memories. The final-method slip says to exclude them from drawing, but keep them for interpreting the tickets. This preserves LD/RD/AD/HD’s earlier jobs.'),
('RV-13','Fix before testing','Rouen needs a clear extraction and counting convention','PZ-15',
 'R2 mentions fighting, people, poultry and Inn: these are not four Saxon-column words as the old description claims. The ticket gives coordinates, but neither it nor the card clearly states icon-to-coordinate distances or whether to count endpoints. The 15-row ticket itself is usable; extra vocabulary is not automatically stale.',
 'Accept either member of each matching pair. Use reading order fight → people → poultry → inn, then H6→I6 = 1, F11→F7 = 4, I3→A3 = 8, H9→B9 = 6. The supplied slip states four grid journeys and excludes the starting square. Keep unused cow/forest icons as scenery only after testing for distraction.'),
('RV-14','Test risk','Counting is sound in principle, but the smallest details matter','PZ-19',
 'At full source resolution R1 shows two bolts (one on the nearer round tower, one at the tall tower’s top), R6 shows three boars among deer, and RD shows five boats. The intended before-911 / 911 / 1199 order gives 5, 6, 2 after doubling boars. Reduced previews conceal some of these details.',
 'Keep this as the accessible parallel task on Rollo. Give players a magnifier and test the printed 5×3.5-inch cards. Add a first hint that specifies the three cards and the history dates; do not make guessed animal silhouettes or external history carry the solve.'),
('RV-15','Fix before printing','Print filenames can deliver an incomplete deck or an answer','Print packaging',
 'Norse_Postcards_Full_Print.pdf has six pages: three two-sided cards, not the 22-card deck. The four LongEdge sheet PDFs contain 4 + 4 + 4 + 2 card backs: only 14 cards. Aud_Ticket_Print.pdf includes a third page containing ANSWER 5 2 1. The separate Aud Letter version has two player pages.',
 'Use all 22 individual current card PDFs linked in the Gallery. Neither the misleading “Full” PDF nor the existing four-sheet set is a complete deck. The review folder includes Aud_Ticket_PLAYER_ONLY.pdf. Keep all *_ANSWER PDFs and review notes out of the game.'),
('RV-16','Documentation','Competing versions obscure what is actually built','AGENTS / system / final-riddle / guide',
 'The shared guide says 18 cards, while the produced deck is 18 route cards plus four decoys. Tabs mix interleaved dates with the newer blocked journey, and old 7×7 board, 467/531 Aud codes and unbuilt-map claims remain next to current material. Marks and all 22 card backs are now built.',
 'This review works from the current 22-card print set and labels that assumption. It preserves the original rather than silently adopting a new invariant. Current facts, proposed changes, open decisions and old source material are separated here. Approval is still needed to reconcile the 18-card guide with production.'),
('RV-17','Production gap','The invitation is a concept rather than a packed reward','ST-05',
 'The indexed production PDFs contain no final personal letter/plane-ticket reward. H6 already promises one more puzzle, so giving it too early creates a false ending.',
 'Release H6 only when the last required Harald puzzle is complete. Write the invitation and fictional ticket after the dig/reward choice; do not invent a booked flight, date or excavation site. The final container should contain a satisfying personal ending, not another unexplained task.'),
('RV-18','Test risk','Difficulty is uneven rather than uniformly hard','PZ-20 / whole game',
 'MEAD may be guessed from HONEY alone by an experienced player, while FERMENTED from sugar + bubbles + time is interpretive. Meanwhile the board reconstruction, Aud map and final ordering each involve several transformations. These are designer judgments, not observed solve times.',
 'Let MEAD be a shorter confidence-building parallel win. Accept fermentation/fermenting as intermediate readings; the four-letter lock validates the drink. Do not require exact vocabulary before attempting the lock. Put clearer instructions around physical operations, preserving the deductions themselves.'),
('RV-19','Test risk','The finale model knows more than the printed clues','Tools/final_riddle_clues.py',
 'The enumerator assumes the real-card sets, leg assignment, leg order and intended digit per route. It also encodes a direct Bayeux→Winchester adjacency while the current journal only implies before/after. It is useful evidence about its model, not an end-to-end player simulation.',
 'Independent review re-ran it and also tested the weaker printed ferry relationships; Rollo still has one real-card order. The proposed journal explicitly names anchors and removes dependence on knowing which places count as Mediterranean. Separate ordering, visual filtering, map recognition and physical delivery tests.'),
]

FINDINGS += [
('RV-20','Approved change','Treasure tally replaces weighing','G7 / PZ-03 / PR-20',
 'User approved summing coin values and turning the displayed total upside down. Calculator or a four-wheel 3D-printed tally remains a choice; neither is confirmed built.',
 'Use the approved 3705 → SOLE mechanism. PR-24 tracks display choice; PR-25 tracks selection marks, coin inventory and fictional values. Retire the old scale/truncation cue. A1 requires new puzzle copy; A3 should refer to the tally.'),
('RV-21','Approved change','HRAFN now opens a four-digit board pouch','G8 / PZ-02 / PR-26',
 'User approved the pictured five-perch mechanism. HRAFN visits five of eight perches and reads four directly connecting flight labels: 2, 6, 4, 8.',
 'Release The raven’s flights with the initial Harald packet after SOLE, outside the board pouch. Decode HRAFN using the corrected map and H4/H5; follow H–R–A–F–N for 2648. Use one four-digit lock directly on the board pouch. Cryptex and its separate key/closure are superseded. H4/H5 need no change.')]

# key, difficulty, readiness, concise assessment
PUZZLE_REVIEWS = {
'opening':('Easy','Keep','Good first win. L1 and the two street numbers support 1021. Test whether “first stop” supplies enough ordering guidance; hint before making the copy more explicit.'),
'beasts':('Medium','Keep; test discovery','The F1 → BEAR → B/E/A/R → 3212 chain is internally consistent. The tiny publisher imprint needs a fair nudge and a magnifier, not a random search of the whole deck.'),
'topedge':('Medium idea; high physical risk','Cue + physical proof','The intended 1576 is recorded, but the required action is absent from L2/L3. Do not confuse a digital alignment proof with light passing through the finished stock.'),
'wordlock':('Medium–hard','Clarify operation','The four grid distances support 1486. Current text uses mixed word-pair members. Make the count convention and reading order explicit enough that failures are reasoning failures, not rule guesses.'),
'counting':('Easy–medium','Keep; print-size test','The expected 5 boats / 3 boars × 2 / 2 bolts are present. History order is separate from Liv’s final travel order. A useful job for a second pair of players.'),
'rebus':('Hard; not calibrated','Optional in proposed core','Interesting thematic combination, but no defensible numeric answer yet. Do not invent a distance or configure a lock from this review.'),
'treasure':('Hard','Clarify and walk on paper','Six legs, three tallies and lookalike destinations make this one of the heaviest tasks. The first worked row helps. Current A2 lacks the promised southward distinction; 521 needs a physical walkthrough.'),
'hoard':('Medium idea; needs physical proof','Tally approved; props unfinished','Supersedes weighing. Match the cache mark, sum selected coin values to 3705, set the tally and rotate it to read SOLE. Coin values, inventory, marks and display choice remain open; revise A1/A3 before printing.'),
'comb':('Unknown','Park mandatory gate','No verified letter locations or working comb exist. BOOK cannot yet be assessed as an actual puzzle. Keep the decoy card; defer its extraction rather than hiding an unfinished gate in the path.'),
'runes':('Medium; added extraction untested','Five-perch conversion approved','Corrected rune map plus H4/H5 yields HRAFN. Use these letters as five perches, reading the four direct flight labels as 2648. One four-digit lock opens the board kit. The perch card is available before this gate; no Norse translation is required.'),
'hnefatafl':('Hard','State rules; test overlay','The fixed-piece board has one three-move escape: 253. Reconstructing the missing strip plus planning the route is enough challenge; contradictory capture rules add confusion.'),
'mead':('Easy–medium','Keep as parallel win','HONEY + DRINK + FERMENTED leads to MEAD. H2’s sentence acrostic works; typography should keep the five sentence starts visible. Some players will infer MEAD early, which is acceptable.'),
'finalroute':('Hard','Order model passes; recognition open','Filter four decoys, infer four within-trail orders, join tickets and draw. Split maps among players, then reconvene for digit order. Do not require rebuilding exact travel dates.'),
'reveal':('No puzzle','Reward still needed','End on Liv’s invitation. No fifth map task is needed for the proposed 60–90-minute game unless it improves the reward.'),
}

FLOW = [
('S0','Outside the bag','L1 + two luggage tags + Start here slip + optional hints access.','Match the first place to the first tag: 1021.','G1 · 4-digit bag lock','LD, Leif map and L’Anse museum ticket.','2–4 solve together; teach keep/read/both sides.'),
('S1','The beasts','LD + Leif map + museum ticket.','Publisher imprint F1 → bear → ticket letters: 3212.','G2 · 4-digit sleeve','L2 and L3, Two skies cue, usable light source if not already outside.','One finds the imprint, one locates the beast, one checks the index.'),
('S2','Joined skies','L2 + L3; actual tested stock and light.','Align top edges to read intended 1576.','G3 · 4-digit Rollo case','All seven Rollo cards R1–R6 + RD; Rollo map and Rouen ticket.','Physical cooperation; provide hint/rescue if the prototype fails.'),
('S3','Two Rollo tasks in parallel','R2 + map + ticket on one side; R1/R6/RD on the other. R3–R5 also available.','Word journeys 1486 AND historical counts 562. Rebus discovery is optional, with no numeric lock.','G4 · 4-digit AND G5 · 3-digit, both securing the Aud pouch','A2, Aud map and Aud player ticket.','Two people take one task each; four form two pairs. Both codes must be required by the closure.'),
('S4','Aud’s treasure route','A2 + map + ticket, with its first tally row filled.','Trace the six legs; intended bridges/fords/gates total 521.','G6 · 3-digit coin cache','A1, A3, mixed coin hoard, merchant’s value key and treasure tally. Cache bears the coin-selection mark.','Reader, navigator and crossing-tally checker can work together. Coin-selection marks and fictional values still need completing.'),
('S5','The treasure tally','Revised A1 + A3 + cache mark + coin value key + selected coins + calculator or four-wheel tally.','Sort; add selected values to 3705; display the total; rotate the whole tally 180 degrees: SOLE.','G7 · dedicated 4-letter lock','AD; H2, H3, H4, H5 and HD; corrected Harald map; The raven’s flights card. Optional comb only after it works.','One sorts, another checks the sum, a third records it. No weighing or truncation. Tally choice, marks, values and print updates are unfinished.'),
('S6','Two Harald branches','H4/H5 + corrected map front + The raven’s flights for runes; H2/H3/HD for the drink.','Runes HRAFN → H–R–A–F–N flights → 2648 → board kit; drink MEAD → journal. Either branch may finish first.','G8 · 4-digit board-pouch lock, 2648; G9 · separate 4-letter journal wallet','G8: H1, museum ticket, board, 16 dark + 6 light + king, and challenge rules. G9: family journal.','Perch card stays outside the board pouch. No cryptex or intermediate key. Board still follows runes so the front/back map is not required simultaneously.'),
('S7','The king escapes','H1 + map back + museum offset + board kit.','Reconstruct fixed pieces; F6 → H6 → H11 → K11 gives 253.','G10 · 3-digit final-evidence sleeve','H6, all three transition tickets, final-method slip and markers.','Board follows runes so the front/back map is not needed by two tasks simultaneously.'),
('S8','Reconstruct the journeys','All 22 cards, all four maps, journal from G9 and tickets from G10.','Keep 18 route cards; order, trace, recognize and arrange intended digits 1 / 9 / 7 / 2.','G11 · 4-digit final container','Personal letter and fictional invitation/ticket reward.','Pair players with maps, then reunite for the four-digit answer. North stays up.'),
]

# Complete first-release mapping, including non-gating cards.
RELEASES = {
'L1':'S0 · outside', 'LD':'G1', 'L2':'G2','L3':'G2',
**{x:'G3' for x in ['R1','R2','R3','R4','R5','R6','RD']},
'A2':'G4 + G5 together','A1':'G6','A3':'G6','AD':'G7',
**{x:'G7' for x in ['H2','H3','H4','H5','HD']},'H1':'G8 board kit','H6':'G10'}

HINTS = [
('G1 · Opening','Match the postcard’s place to one luggage tag.','Use the two street numbers, not the names.','L’Anse aux Meadows goes first; Rouen goes second.','1021: 10, then 21.'),
('G2 · Beasts','Look for a small publisher’s imprint on the Greenland postcard.','Series F, No. 1 points to square F1 on the sea chart.','Identify that animal, then look up its letters on the back of the museum ticket.','BEAR: B=3, E=2, A=1, R=2. Code 3212.'),
('G3 · Joined skies','The cloud fragments on the two northern pictures belong together.','Try picture sides facing each other, one turned half a turn.','Align the top edges against a bright light and read along the join.','The intended reading is 1576. If a finished print cannot show it, that is a prop fault, not a missed deduction.'),
('G4 · Rouen word journeys','Four matching word-pairs from the ticket appear in the Rouen message. Either member of a pair counts.','Use fight/combat, people/folk, poultry/hen and inn/tavern in that order. The ticket supplies I6, F7, A3 and B9.','Find each matching map picture. Count grid steps from its square to its target; exclude the starting square.','H6→I6 = 1; F11→F7 = 4; I3→A3 = 8; H9→B9 = 6. Code 1486.'),
('G5 · Picture counts','Use the Chalus, Roumare Forest and Walcheren cards. Each message names something drawn on its front.','Count bolts, boars and boats. The Roumare message asks you to double the boar count.','Order the three by the historical periods in the Fun Facts: before 911, 911, then 1199.','Five boats, three boars doubled to six, two bolts. Code 562. On Chalus, inspect the near round tower and the top of the tall tower.'),
('G6 · Aud’s route','The ticket is a route, not a list of separate destinations. Start with the chapel-to-chapel leg already filled in.','Keep a separate tally for bridges, fords and gates. Count each crossing you traverse, not every symbol visible nearby.','At the standing stone, compare the village choices with A2’s forest observation. The intended route goes south toward H9, then on to the ruin and the cave.','Intended totals: 5 bridges, 2 fords, 1 gate. Code 521. Designer must first verify this on the printed route.'),
('G7 · Treasure tally','Sort the coins by their marks. The mark on the cache tells you which coins to use.','Use the merchant’s value key to add their worth, not their weight. Record the total on the treasure tally.','Turn the whole display upside down and read the four characters from left to right. Nothing needs rounding or crossing out.','The intended total is 3705. In suitable calculator-style lettering it should read SOLE after a 180-degree turn. The coin inventory, value key and display must be physically checked before playing this gate.'),
('G8 · Runes and flights','The underlined word on the Sicily postcard matters to the map’s unusual column labels.','Read the columns R, A, V, E, N in that order. On Hedeby’s key, each stem’s left branches select the row; its right branches select the letter.','Use the five decoded letters as perches on The raven’s flights. Move directly from each letter to the next and read one digit from each connecting flight. Do not add them.','Corrected map: R6→H, A10→R, V9→A, E3→F, N2→N. HRAFN gives H→R = 2, R→A = 6, A→F = 4, F→N = 8. Code 2648 opens the board pouch. Use the corrected map; the original E7 decoy creates ambiguity.'),
('G9 · The drink','Three postcards contribute three ideas: Kyiv, Staraya Ladoga and Constantinople.','Solve Kyiv’s riddle; look at the first letters of Ladoga’s five sentences; interpret sugar, bubbles and time.','You need a four-letter drink made from fermented honey.','HONEY + DRINK + FERMENTED leads to MEAD. Fermentation or fermenting is a valid intermediate interpretation.'),
('G10 · King’s escape','The map-back stain hides three columns. The museum ticket holds their mirrored impression.','Hold the ticket to light and align the grid to recover the missing pieces. Only the king moves; all others are obstacles.','Work backward from a corner. Try moving the king from F6 toward H6.','F6 → H6 → H11 → K11. Distances 2, 5, 3 give 253. No captures, jumps or moving blockers.'),
('G11 · Whole journey','Use stamps to form four groups, then compare the small marks with the journal’s family drawings.','Leave horned-helmet and double-axe cards out of the drawn routes. Keep those cards nearby to interpret ticket endpoints.','Use the first origin and last destination of each travel ticket to chain the four journeys. Journal and card clues order the places within each. Join place dots with straight lines, north up.','Real orders: L1–L2–L3; R1–R2–R3–R4–R5–R6; A1–A2–A3; H1–H2–H3–H4–H5–H6. Intended shapes 1,9,7,2 in Leif–Rollo–Aud–Harald order: 1972. Physical digit recognition remains to be tested.'),
]
