const fs=require('fs'),vm=require('vm'),path=require('path');
const dir=__dirname,data=JSON.parse(fs.readFileSync(path.join(dir,'patch-layout.json'),'utf8'));
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(dir,'jsqr-1.4.0.js'),'utf8'),ctx);
function compose(bits){let m=[...data.base];data.tiles.forEach((t,i)=>{if(bits&(1<<i))t.forEach(k=>m[k]=data.target[k]);});return m;}
function pixels(m,scale){let n=33*scale,a=new Uint8ClampedArray(n*n*4).fill(255);for(let r=0;r<25;r++)for(let c=0;c<25;c++)if(m[r*25+c])for(let y=(r+4)*scale;y<(r+5)*scale;y++)for(let x=(c+4)*scale;x<(c+5)*scale;x++){const k=(y*n+x)*4;a[k]=a[k+1]=a[k+2]=0;}return{a,n};}
const seen=new Set();for(const tile of data.tiles){const set=new Set(tile),queue=[tile[0]],connected=new Set(queue);for(let i=0;i<queue.length;i++){let k=queue[i],r=Math.floor(k/25),c=k%25;for(let n of [r>0?k-25:-1,r<24?k+25:-1,c>0?k-1:-1,c<24?k+1:-1])if(set.has(n)&&!connected.has(n)){connected.add(n);queue.push(n);}}if(connected.size!==set.size)throw Error('Disconnected patch');for(const k of tile){if(seen.has(k))throw Error('Overlapping patches');seen.add(k);}}
if(compose(63).some((v,i)=>v!==data.target[i]))throw Error('Incomplete target');
data.results=[];for(let bits=0;bits<64;bits++){let {a,n}=pixels(compose(bits),6);data.results.push(ctx.jsQR(a,n,n)?.data||null);}
if(data.results[0]!==data.urls[0]||data.results[63]!==data.urls[1]||data.results.slice(0,63).includes(data.urls[1]))throw Error('Decode requirements failed');
data.coverage=seen.size;data.changes=data.base.filter((v,i)=>v!==data.target[i]).length;
fs.writeFileSync(path.join(dir,'validated-layout.json'),JSON.stringify(data,null,2));
const colors=['#a84420','#256c70','#755591','#9c6515','#32724e','#37599b'];
let html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aurora · Six QR patches</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f2ee;color:#16253c;font:16px/1.5 system-ui,Segoe UI,sans-serif}main{max-width:1180px;margin:auto;padding:30px 24px 50px}header{display:flex;justify-content:space-between;gap:12px;font-size:12px;text-transform:uppercase;letter-spacing:.1em;margin-bottom:26px;color:#626d7a}header b{color:#a84420}h1{font-size:clamp(27px,4vw,40px);letter-spacing:-.04em;line-height:1.15;margin:0 0 12px}h2{font-size:19px;margin:0 0 10px}p{margin:0 0 15px}.muted{color:#596676;max-width:850px}.metrics{display:flex;gap:12px;flex-wrap:wrap;margin:22px 0}.metrics span{background:#e5e9ee;padding:7px 12px;border-radius:6px;font-size:14px}.layout{display:grid;grid-template-columns:1fr 1.15fr;gap:24px}.panel{padding:22px;background:white;border:1px solid #d5dbe2;border-radius:12px;min-width:0}button{cursor:pointer;font:inherit;background:#fff;color:#16253c;border:1px solid #aeb9c7;border-radius:7px;padding:9px 12px}button:focus-visible,a:focus-visible{outline:3px solid #d68e29;outline-offset:3px}.toolbar{display:flex;flex-wrap:wrap;gap:8px;margin:17px 0}button[aria-pressed=true]{background:#16253c;color:white}.qr{max-width:400px;margin:auto}.qr svg{width:100%;display:block}.tiles{display:grid;grid-template-columns:1fr 1fr;gap:12px}.tile{display:flex;flex-direction:column;text-align:left;min-width:0;padding:12px}.tile[aria-pressed=true]{background:#f2f5f7;color:#16253c;border:2px solid #16253c;padding:11px}.tile .title{display:flex;justify-content:space-between;gap:5px;font-size:13px;font-weight:700}.tile svg{display:block;width:100%;height:110px;margin:8px 0}.tile small{font-size:11px;color:#596676}.status{border-left:3px solid #256c70;padding:10px 13px;background:#eff5f4;margin-top:15px}.status strong{display:block}.status code{font-size:12px;overflow-wrap:anywhere}.notes{margin-top:22px}.notes p{font-size:14px}.footnote{font-size:12px;color:#596676;margin-top:12px}.legend{font-size:12px;color:#596676}a{color:#a84420}details{margin-top:18px}summary{cursor:pointer;font-weight:650}table{width:100%;border-collapse:collapse;font-size:13px;margin-top:12px}td,th{padding:8px;border:1px solid #d5dbe2;text-align:left}th{background:#edf0f4}.proof{font-size:13px;color:#256c70}.scroll{overflow:auto}@media(max-width:750px){main{padding:22px 16px}.layout{grid-template-columns:1fr}.panel{padding:16px}header{font-size:10px}.tile svg{height:95px}.metrics{gap:7px}.metrics span{font-size:12px}}
</style></head><body><main><header><span>Escape Backpack / Aurora</span><b>Patch feasibility prototype</b></header><h1>Six patches. Most of the QR stays visible.</h1><p class="muted">Add the replacement pieces to the base code. This layout covers 44% of the QR face and leaves 56% exposed. Select a piece below to add or remove it.</p><div class="metrics"><span><b>6</b> connected patches</span><span><b>44%</b> covered · 275 of 625 squares</span><span><b>64 / 64</b> presence/absence states tested</span></div><div class="layout"><section class="panel"><h2>Assembled panel</h2><p class="legend">Coloured outlines identify the patch footprints. White space outside the QR is kept clear.</p><div class="toolbar"><button id="none">Remove all</button><button id="all">Add all six</button><button id="outlines" aria-pressed="true">Patch outlines on</button></div><div class="qr" id="qr"></div><div class="status" aria-live="polite" id="status"></div><p class="footnote">Reader result was tested on the clean black-and-white image, without coloured outlines. URLs are proposed and have not been deployed.</p></section><section class="panel"><h2>Replacement pieces</h2><p class="legend">All six contain black and white squares. Grey backgrounds show empty space around each piece, not part of the tile.</p><div class="tiles" id="tiles"></div></section></div><section class="notes panel"><h2>What this proves—and what still needs work</h2><p><b>Software result:</b> the bare code reaches the wrong URL; all 62 partial combinations are unreadable; the complete code reaches the correct URL. This covers correctly positioned tiles only, tested with jsQR 1.4.0.</p><p><b>Physical limitation:</b> some connections are only one QR square wide. These outlines demonstrate coverage and decoding; they are not finished peg-board parts. They may need backing, stronger connectors or simpler shapes within the 50% limit.</p><p><b>Next check:</b> print a flat prototype, then try the endpoints and all six “one tile missing” states with different phone cameras. Wrong positions, rotation, shadows and raised tile edges have not been validated.</p><details><summary>Exact design settings and patch sizes</summary><div class="scroll"><table><thead><tr><th>Setting</th><th>Value</th></tr></thead><tbody><tr><td>Base URL</td><td>https://escapepack.ca/7m2q9v4c</td></tr><tr><td>Correct URL</td><td>https://escapepack.ca/p6r8t3x5</td></tr><tr><td>QR settings</td><td>25 × 25, low correction; base mask 5, target mask 3</td></tr><tr><td>Actual black/white changes</td><td>215 squares; footprint includes 60 unchanged connecting squares</td></tr><tr><td>Patch areas A–F</td><td>78, 47, 46, 38, 30, 36 squares</td></tr><tr><td>Coverage denominator</td><td>625 QR squares; excludes the surrounding white border</td></tr><tr><td>Generator</td><td>qrcode 1.5.1; settings must be fixed when reproducing</td></tr></tbody></table></div></details></section></main><script>
const data=${JSON.stringify(data)},colors=${JSON.stringify(colors)};let bits=63,outlines=true;
const edge=(set,k)=>{const r=Math.floor(k/25),c=k%25;let p='';if(!set.has(k-25))p+='M'+c+' '+r+'h1';if(c===24||!set.has(k+1))p+='M'+(c+1)+' '+r+'v1';if(!set.has(k+25))p+='M'+c+' '+(r+1)+'h1';if(c===0||!set.has(k-1))p+='M'+c+' '+r+'v1';return p;};
function tileSvg(i){const t=data.tiles[i],rs=t.map(k=>Math.floor(k/25)),cs=t.map(k=>k%25),r0=Math.min(...rs),r1=Math.max(...rs),c0=Math.min(...cs),c1=Math.max(...cs),set=new Set(t);return '<svg viewBox="'+(c0-.6)+' '+(r0-.6)+' '+(c1-c0+2.2)+' '+(r1-r0+2.2)+'" role="img" aria-label="Patch '+String.fromCharCode(65+i)+' outline and QR pattern" style="background:#e9edf0"><g shape-rendering="crispEdges">'+t.map(k=>'<rect x="'+k%25+'" y="'+Math.floor(k/25)+'" width="1" height="1" fill="'+(data.target[k]?'#111':'white')+'"/>').join('')+'</g><path d="'+t.map(k=>edge(set,k)).join('')+'" fill="none" stroke="'+colors[i]+'" stroke-width=".15"/></svg>';}
function draw(){let m=[...data.base];data.tiles.forEach((t,i)=>{if(bits&(1<<i))t.forEach(k=>m[k]=data.target[k]);});let svg='<svg viewBox="-4 -4 33 33" role="img" aria-label="QR assembled with '+bits.toString(2).split('1').length.toString()+' patch state"><rect x="-4" y="-4" width="33" height="33" fill="white"/><g shape-rendering="crispEdges">'+m.map((v,k)=>v?'<rect x="'+k%25+'" y="'+Math.floor(k/25)+'" width="1" height="1" fill="#111"/>':'').join('')+'</g>';if(outlines)data.tiles.forEach((t,i)=>{if(bits&(1<<i)){const set=new Set(t);svg+='<path d="'+t.map(k=>edge(set,k)).join('')+'" fill="none" stroke="'+colors[i]+'" stroke-width=".12"/>';}});document.getElementById('qr').innerHTML=svg+'</svg>';const count=Array.from({length:6},(_,i)=>!!(bits&(1<<i))).filter(Boolean).length;document.querySelector('#qr svg').setAttribute('aria-label','QR assembled with '+count+' patches');const result=data.results[bits];document.getElementById('status').innerHTML='<strong>'+count+' of 6 patches attached · '+(result?(bits===63?'correct destination':'wrong destination'):'unreadable')+'</strong>'+(result?'<code>'+result+'</code>':'<span>Continue repairing the panel.</span>');document.getElementById('tiles').innerHTML=data.tiles.map((t,i)=>'<button class="tile" data-tile="'+i+'" aria-pressed="'+!!(bits&(1<<i))+'"><span class="title"><span>Patch '+String.fromCharCode(65+i)+'</span><span>'+(bits&(1<<i)?'Attached':'Add +')+'</span></span>'+tileSvg(i)+'<small>'+t.length+' squares · '+(100*t.length/625).toFixed(1)+'% of QR</small></button>').join('');document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.tile);bits^=1<<i;draw();document.querySelector('[data-tile="'+i+'"]').focus();});}
document.getElementById('none').onclick=()=>{bits=0;draw();};document.getElementById('all').onclick=()=>{bits=63;draw();};document.getElementById('outlines').onclick=function(){outlines=!outlines;this.setAttribute('aria-pressed',outlines);this.textContent='Patch outlines '+(outlines?'on':'off');draw();};draw();
</script></body></html>`;
fs.writeFileSync(path.join(dir,'Aurora_QR_Patches.html'),html);
console.log(JSON.stringify({area:data.coverage,coverage:data.coverage/625,changes:data.changes,partialUnreadable:data.results.slice(1,63).filter(x=>x===null).length,connected:true,disjoint:true,fullTarget:true}));
