const fs=require('fs'),path=require('path'),{createRequire}=require('module');
const r=createRequire('C:/Users/simon/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json'),{chromium}=r('playwright'),JSZip=r('jszip');
const dir=__dirname,url='file:///'+path.join(dir,'Aurora_QR_Patch_Editor.html').replaceAll('\\','/');
const assert=(x,msg)=>{if(!x)throw Error(msg);};
async function main(){const b=await chromium.launch({channel:'msedge',headless:true}),page=await b.newPage({viewport:{width:1400,height:1050},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(url);await page.evaluate(()=>localStorage.clear());await page.reload();assert(await page.locator('#stats').innerText().then(t=>t.includes('0 / 58')),'Expected 58 default changes');
const k=await page.evaluate(()=>qr.base.findIndex((v,k)=>v!==qr.target[k]&&!corner(k))),n=await page.evaluate(()=>qr.size);
async function clickCell(key){const bb=await page.locator('#editor').boundingBox(),u=bb.width/(n+8);await page.mouse.click(bb.x+(key%n+4.5)*u,bb.y+(Math.floor(key/n)+4.5)*u);}
await clickCell(k);assert(await page.evaluate(k=>owner[k]===0,k),'Paint A');await page.locator('#undo').click();assert(await page.evaluate(k=>owner[k]===-1,k),'Undo');await page.locator('#redo').click();assert(await page.evaluate(k=>owner[k]===0,k),'Redo');await page.locator('[data-patch="1"]').click();await clickCell(k);assert(await page.evaluate(k=>owner[k]===1,k),'Transfer to B');
const bb=await page.locator('#editor').boundingBox(),u=bb.width/(n+8);await page.mouse.move(bb.x+13.5*u,bb.y+13.5*u);await page.mouse.down();await page.mouse.move(bb.x+15.5*u,bb.y+13.5*u,{steps:8});await page.mouse.up();assert(await page.evaluate(()=>[234,235,236].every(k=>owner[k]===1)),'Drag painting');
await page.locator('#erase').click();await clickCell(k);assert(await page.evaluate(k=>owner[k]===-1,k),'Erase');await page.locator('#undo').click();
let download=page.waitForEvent('download');await page.locator('#save-json').click();const d=await download,first=JSON.parse(fs.readFileSync(await d.path(),'utf8'));assert(first.format==='aurora-qr-patches','JSON download');await page.reload();assert(await page.evaluate(()=>owner.some(v=>v>=0)),'Autosave restore');
const old=JSON.parse(fs.readFileSync(path.join(dir,'validated-layout.json'),'utf8'));const imported={format:'aurora-qr-patches',schemaVersion:1,settings:{baseUrl:old.urls[0],targetUrl:old.urls[1],ec:'L',baseMask:'5',targetMask:'3'},size:25,baseMatrix:old.base,targetMatrix:old.target,moduleSizeMm:3,patches:old.tiles.map((t,i)=>({id:'ABCDEF'[i],enabled:true,cells:t.map(k=>[Math.floor(k/25),k%25])}))};
await page.locator('#file').setInputFiles({name:'layout.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});assert(await page.locator('#scan').innerText().then(t=>t.includes('Correct destination')),'Imported target decode');await page.locator('#test').click();await page.waitForFunction(()=>report!==null&&!busy);assert(await page.evaluate(()=>report.states===64&&report.earlyTargetStates===0&&report.fullAssembly==='target'),'Known 64-state result');
download=page.waitForEvent('download');await page.locator('#export').click();const zipDownload=await download,zip=await JSZip.loadAsync(fs.readFileSync(await zipDownload.path()));assert(Object.keys(zip.files).length===18,'ZIP entries');const out=JSON.parse(await zip.file('layout.json').async('string'));assert(out.patches.flatMap(p=>p.cells).length===275,'Export coverage');for(let i=0;i<6;i++){const svg=await zip.file('patch-'+ 'ABCDEF'[i]+'.svg').async('string');assert((svg.match(/<rect /g)||[]).length===old.tiles[i].length,'Patch artwork footprint');assert(!svg.includes('stroke='),'No coloured outline in print pattern');}
const bad={...out,patches:out.patches.map(p=>({...p,cells:[...p.cells]}))};bad.patches[1].cells.push(bad.patches[0].cells[0]);await page.locator('#file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});assert(await page.locator('#error').innerText().then(t=>t.includes('overlapping')),'Reject invalid import');assert(await page.evaluate(()=>owner.filter(x=>x>=0).length===275),'Invalid import preserves layout');
await page.evaluate(()=>localStorage.clear());await page.reload();const diffs=await page.evaluate(()=>qr.base.flatMap((v,k)=>v!==qr.target[k]?[k]:[]));const current=await page.evaluate(()=>layout());current.patches[0].cells=diffs.map(k=>[Math.floor(k/25),k%25]);current.patches[1].cells=[[8,10]];if(diffs.includes(210))current.patches[1].cells=[[8,11]];
await page.locator('#file').setInputFiles({name:'current.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(current))});await page.locator('#test').click();await page.waitForFunction(()=>report!==null&&!busy);assert(await page.evaluate(()=>report.fullAssembly==='target'&&report.earlyTargetStates>0),'Reports skippable filler tile');
await page.screenshot({path:path.join(dir,'editor-qa.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'Mobile width');
await page.goto('file:///'+path.join(dir,'..','Aurora_Visual_Guide.html').replaceAll('\\','/')+'#qr');const f=page.frameLocator('#patch-preview');await f.locator('#editor').waitFor();assert(await f.locator('#export').count()===1,'Embedded editor present');await f.locator('#detach-all').click();assert(await f.locator('#scan').innerText().then(t=>t.includes('Base destination')),'Embedded interaction');assert(errors.length===0,'Page script errors: '+errors.join(';'));
console.log('PASS: paint, drag, erase, transfer, undo/redo, browser restore, JSON import validation, 64-state scan, shortcut detection, SVG/ZIP export, mobile width and embedded controls.');await b.close();}
main().catch(e=>{console.error(e);process.exit(1);});
